name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
env: 
  PASSWORD: ${{secrets.PASSWORD}}
  EMAIL: ${{secrets.EMAIL}}
  run: npm run cypress:run -- --env user_email=$EMAIL,user_password=$PASSWORD